---

# 
#  @author      : 00xWolf
#    GitHub    : @mmsaeed509
#    Developer : Mahmoud Mohamed
#  﫥  Copyright : Mahmoud Mohamed
#

version: "1"
rules:
  - base: master
    upstream: anuraghazra:master
    mergeMethod: push
